package problems

object Problem2 extends App {

  
  /*
   * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
   * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
   * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
   * find the sum of the even-valued terms.
   */
  
  def fib(a:Int,b:Int) : Stream[Int] ={
    
    def fibAcc(x:Int,y:Int, acc:Stream[Int]):Stream[Int] = {
      val z=x+y
      if(z<=4e6)
    	  fibAcc(y,z,acc:+y)
      else
    	  acc:+y
    }
    
    fibAcc(a,b,Stream[Int](a))
    
  }                                               
  
  println(fib(1,2).filter(_%2==0).sum)   

  
}